name: flutter_inappwebview
description: A Flutter plugin that allows you to add an inline webview, to use an headless webview, and to open an in-app browser window.
version: 5.0.0
homepage: https://github.com/pichillilorenzo/flutter_inappwebview

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.12.13+hotfix.5"

dependencies:
  flutter:
    sdk: flutter
<<<<<<< HEAD
  uuid: ^2.0.0
  mime: ^0.9.6+2
=======

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.0

  flutter_downloader: ^1.4.4
  path_provider: ^1.6.9
  permission_handler: ^5.0.0+hotfix.6
  url_launcher: ^5.4.11
  html: ^0.14.0+4
  flutter_scan_bluetooth: ^1.1.0
  socket_io_client: ^0.9.11
  firebase_messaging: ^7.0.3
  overlay_support: ^1.0.5
  flutter_inappwebview:
    path: ../
  get: ^3.15.0
  shared_preferences: ^0.5.12+4

dev_dependencies:
  e2e: '^0.2.0'
  flutter_test:
    sdk: flutter
  test: any
>>>>>>> main

# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  plugin:
    platforms:
      android:
        package: com.pichillilorenzo.flutter_inappwebview
        pluginClass: InAppWebViewFlutterPlugin
      ios:
        pluginClass: InAppWebViewFlutterPlugin

  assets:
    - packages/flutter_inappwebview/t_rex_runner/t-rex.html
    - packages/flutter_inappwebview/t_rex_runner/t-rex.css
  # To add assets to your plugin package, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg
  #
  # For details regarding assets in packages, see
  # https://flutter.io/assets-and-images/#from-packages
  #
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.io/assets-and-images/#resolution-aware.

  # To add custom fonts to your plugin package, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts in packages, see
  # https://flutter.io/custom-fonts/#from-packages
